# Site settings
title: dippData
email: mail@jorgeboucas.com
description: > # this means to ignore newlines until "baseurl:"
    dippData
    big Data analysis
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Jorge Boucas
email: mail@jorgeboucas.om
facebook_username:
twitter_username: jorgeboucas
github_username: jorgeboucas
address:
  - line: Niehler Str. 33 
  - line: D-50733 Cologne, Germany
  # Feel free to add more lines here 
telephone: +49 (0)178 183 5002
copyright: Jorge Boucas

# API settings
google_api_key: AIzaSyA_rtAAV0VcTYHUy6SlOwCnbL3BhrX1SKs

# Build settings
markdown: kramdown
